# Site settings
title: Justin Patenaude
email: me@justinpatenaude.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description. Hello.
baseurl: "/jekyll/" # the subpath of your site, e.g. /blog/
url: "http://justinpatenaude.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  JustinPatenaude

# Build settings
markdown: kramdown

# Prose settings
prose:
  root: 'jekyll'
  siteurl: 'http://justinpatenaude.github.io/jekyll/'
  media: '_media'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /_sass
    - .gitignore
    - feed.xml
